/**************************************************/
/* Warning: Autogenerated and subjected to change */
/* Thu Oct 18 2014 22:29:14 GMT+1100 (AEDT)       */
/* Path: ./auto-coded/types/galaxy.hpp            */
/* Generator mark: G541654196                     */
/**************************************************/
#pragma once

#include <auto-coded/types/star.hpp>


struct Galaxy
{
	Star stars[10000];

	Galaxy()=default;
	Galaxy(Galaxy const& value);
	void reset();
	Galaxy operator= (Galaxy const& value);
	Galaxy operator= (Galaxy&& value);
	Galaxy abs() const;
	double min() const;
	double max() const;
	Galaxy operator+= (const Galaxy &right);
	Galaxy operator+= (const double &value);
	Galaxy operator-= (const Galaxy &right);
	Galaxy operator*= (const Galaxy &right);
	Galaxy operator*= (const double &value);
	Galaxy operator/= (const Galaxy &right);
}; // struct Galaxy

Galaxy operator+ (const Galaxy &left,const Galaxy &right);
Galaxy operator+ (const Galaxy &left,const double &value);
Galaxy operator+ (const double &value,const Galaxy &right);
Galaxy operator- (const Galaxy &left,const Galaxy &right);
Galaxy operator* (const double &value,const Galaxy &right);
Galaxy operator* (const Galaxy &left,const Galaxy &right);
Galaxy operator/ (const Galaxy &left,const Galaxy &right);
