/******************************************************/
/* Warning: Autogenerated and subjected to change     */
/* Sat Sep 08 2014 15:11:09 GMT+1000 (AEST)           */
/* Path: ./auto-coded/systems/coullet-sys/manager.cpp */
/* Generator mark: G7692348073                        */
/******************************************************/
#include <auto-coded/systems/coullet-sys/manager.hpp>
#include <auto-coded/systems/coullet-sys/solver.hpp>
#include <auto-coded/systems/coullet-sys/plant_model.hpp>


CoulletSys_manager::CoulletSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t CoulletSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=15000.0;
	double dt=0.001;
	CoulletSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	CoulletSys_plant_init_states(t_start,plant_state);
	CoulletSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	CoulletSys_plant_manual_finalize(*this);
	return integrate_result;
}

void CoulletSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	CoulletSys_plant_rhs(state,state_dot,t,observed_t);
}

void CoulletSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	CoulletSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

