/**********************************************************/
/* Warning: Autogenerated and subjected to change         */
/* Sat Sep 08 2014 15:11:09 GMT+1000 (AEST)               */
/* Path: ./auto-coded/systems/coullet-sys/plant_model.hpp */
/* Generator mark: G54168791813                           */
/**********************************************************/
#pragma once

#include <auto-coded/systems/coullet-sys/manager.hpp>


void CoulletSys_plant_init_states(double /*t*/,position& /*states0*/);

void CoulletSys_plant_manual_inits(
		CoulletSys_manager& system);

void CoulletSys_plant_manual_finalize(
		CoulletSys_manager& system);

void CoulletSys_plant_rhs(
		const position &state,
		position &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void CoulletSys_plant_observer(
		bool &/*simulation_continue*/,
		const position &state,
		const double t,
		const double /*observed_t*/,
		position &output);

