/**************************************************/
/* Warning: Autogenerated and subjected to change */
/* Sun May 27 2014 17:03:06 GMT+1000 (AEST)       */
/* Path: ./config/aaa.cpp                         */
/* Generator mark: G65816892                      */
/**************************************************/
#include <config/aaa.hpp>


namespace config::aaa
{
	const ??? ccc/* warning not initialized */;
	const ??? vvv/* warning not initialized */;
}
