/**************************************************/
/* Warning: Autogenerated and subjected to change */
/* Sun May 27 2014 17:03:06 GMT+1000 (AEST)       */
/* Path: ./config/aaa.hpp                         */
/* Generator mark: G65816892                      */
/**************************************************/
#pragma once

namespace config::aaa
{
	extern const ??? ccc;
	extern const ??? vvv;
}
