/*****************************************************/
/* Warning: Autogenerated and subjected to change    */
/* Sat Sep 08 2014 16:42:06 GMT+1000 (AEST)          */
/* Path: ./auto-coded/systems/rosslersys/manager.cpp */
/* Generator mark: G7692348073                       */
/*****************************************************/
#include <auto-coded/systems/rosslersys/manager.hpp>
#include <auto-coded/systems/rosslersys/solver.hpp>
#include <auto-coded/systems/rosslersys/plant_model.hpp>


RosslerSys_manager::RosslerSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t RosslerSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=15000.0;
	double dt=0.001;
	RosslerSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	RosslerSys_plant_init_states(t_start,plant_state);
	RosslerSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	RosslerSys_plant_manual_finalize(*this);
	return integrate_result;
}

void RosslerSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	RosslerSys_plant_rhs(state,state_dot,t,observed_t);
}

void RosslerSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	RosslerSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

