/**************************************************/
/* Warning: Autogenerated and subjected to change */
/* Sun May 27 2014 17:03:06 GMT+1000 (AEST)       */
/* Path: ./auto-coded/systems/chensys/manager.cpp */
/* Generator mark: G7692348073                    */
/**************************************************/
#include <auto-coded/systems/chensys/manager.hpp>
#include <auto-coded/systems/chensys/solver.hpp>
#include <auto-coded/systems/chensys/plant_model.hpp>


ChenSys_manager::ChenSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t ChenSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=500.0;
	double dt=0.001;
	ChenSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	ChenSys_plant_init_states(t_start,plant_state);
	ChenSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	ChenSys_plant_manual_finalize(*this);
	return integrate_result;
}

void ChenSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	ChenSys_plant_rhs(state,state_dot,t,observed_t);
}

void ChenSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	ChenSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

