#!/bin/bash
####################################################
#  Warning: Autogenerated and subjected to change  #
#  Sun Apr 15 2014 20:03:52 GMT+1000 (AEST)        #
#  Path: ./release_build.sh                        #
#  Generator mark: G6416149813                     #
####################################################

cmake -DCMAKE_BUILD_TYPE=Release -H. -B_built_r && cd _built_r && make && cp ./chaos_arneodo ../
