/*******************************************************/
/* Warning: Autogenerated and subjected to change      */
/* Sun Apr 15 2014 20:07:24 GMT+1000 (AEST)            */
/* Path: ./auto-coded/systems/burkeshawsys/manager.cpp */
/* Generator mark: G7692348073                         */
/*******************************************************/
#include <auto-coded/systems/burkeshawsys/manager.hpp>
#include <auto-coded/systems/burkeshawsys/solver.hpp>
#include <auto-coded/systems/burkeshawsys/plant_model.hpp>


BurkeShawSys_manager::BurkeShawSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t BurkeShawSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=15180.0;
	double dt=0.001;
	BurkeShawSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	BurkeShawSys_plant_init_states(t_start,plant_state);
	BurkeShawSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	BurkeShawSys_plant_manual_finalize(*this);
	return integrate_result;
}

void BurkeShawSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	BurkeShawSys_plant_rhs(state,state_dot,t,observed_t);
}

void BurkeShawSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	BurkeShawSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

