/***********************************************************/
/* Warning: Autogenerated and subjected to change          */
/* Sun Apr 15 2014 20:07:24 GMT+1000 (AEST)                */
/* Path: ./auto-coded/systems/BurkeShawSys/plant_model.hpp */
/* Generator mark: G54168791813                            */
/***********************************************************/
#pragma once

#include <auto-coded/systems/burkeshawsys/manager.hpp>


void BurkeShawSys_plant_init_states(double /*t*/,position& /*states0*/);

void BurkeShawSys_plant_manual_inits(
		BurkeShawSys_manager& system);

void BurkeShawSys_plant_manual_finalize(
		BurkeShawSys_manager& system);

void BurkeShawSys_plant_rhs(
		const position &state,
		position &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void BurkeShawSys_plant_observer(
		bool &/*simulation_continue*/,
		const position &state,
		const double t,
		const double /*observed_t*/,
		position &output);

