/*******************************************************/
/* Warning: Autogenerated and subjected to change      */
/* Sun May 06 2014 13:32:46 GMT+1000 (AEST)            */
/* Path: ./auto-coded/systems/halvorsensys/manager.cpp */
/* Generator mark: G7692348073                         */
/*******************************************************/
#include <auto-coded/systems/halvorsensys/manager.hpp>
#include <auto-coded/systems/halvorsensys/solver.hpp>
#include <auto-coded/systems/halvorsensys/plant_model.hpp>


HalvorsenSys_manager::HalvorsenSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t HalvorsenSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=15180.0;
	double dt=0.001;
	HalvorsenSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	HalvorsenSys_plant_init_states(t_start,plant_state);
	HalvorsenSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	HalvorsenSys_plant_manual_finalize(*this);
	return integrate_result;
}

void HalvorsenSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	HalvorsenSys_plant_rhs(state,state_dot,t,observed_t);
}

void HalvorsenSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	HalvorsenSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

