/***********************************************************/
/* Warning: Autogenerated and subjected to change          */
/* Sun May 06 2014 13:32:46 GMT+1000 (AEST)                */
/* Path: ./auto-coded/systems/halvorsensys/plant_model.hpp */
/* Generator mark: G54168791813                            */
/***********************************************************/
#pragma once

#include <auto-coded/systems/halvorsensys/manager.hpp>


void HalvorsenSys_plant_init_states(double /*t*/,position& /*states0*/);

void HalvorsenSys_plant_manual_inits(
		HalvorsenSys_manager& system);

void HalvorsenSys_plant_manual_finalize(
		HalvorsenSys_manager& system);

void HalvorsenSys_plant_rhs(
		const position &state,
		position &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void HalvorsenSys_plant_observer(
		bool &/*simulation_continue*/,
		const position &state,
		const double t,
		const double /*observed_t*/,
		position &output);

