/******************************************************/
/* Warning: Autogenerated and subjected to change     */
/* Sun Aug 12 2014 18:47:20 GMT+1000 (AEST)           */
/* Path: ./auto-coded/systems/rikitakesys/manager.cpp */
/* Generator mark: G7692348073                        */
/******************************************************/
#include <auto-coded/systems/rikitakesys/manager.hpp>
#include <auto-coded/systems/rikitakesys/solver.hpp>
#include <auto-coded/systems/rikitakesys/plant_model.hpp>


RikitakeSys_manager::RikitakeSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t RikitakeSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=15000.0;
	double dt=0.001;
	RikitakeSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	RikitakeSys_plant_init_states(t_start,plant_state);
	RikitakeSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	RikitakeSys_plant_manual_finalize(*this);
	return integrate_result;
}

void RikitakeSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	RikitakeSys_plant_rhs(state,state_dot,t,observed_t);
}

void RikitakeSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	RikitakeSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

