/*****************************************************************/
/* Warning: Autogenerated and subjected to change                */
/* Sat Sep 08 2014 11:53:59 GMT+1000 (AEST)                      */
/* Path: ./auto-coded/systems/symmetric-flow-sys/plant_model.hpp */
/* Generator mark: G54168791813                                  */
/*****************************************************************/
#pragma once

#include <auto-coded/systems/symmetric-flow-sys/manager.hpp>


void SymmetricFlowSys_plant_init_states(double /*t*/,position& /*states0*/);

void SymmetricFlowSys_plant_manual_inits(
		SymmetricFlowSys_manager& system);

void SymmetricFlowSys_plant_manual_finalize(
		SymmetricFlowSys_manager& system);

void SymmetricFlowSys_plant_rhs(
		const position &state,
		position &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void SymmetricFlowSys_plant_observer(
		bool &/*simulation_continue*/,
		const position &state,
		const double t,
		const double /*observed_t*/,
		position &output);

