/*********************************************************/
/* Warning: Autogenerated and subjected to change        */
/* Sat Sep 08 2014 11:58:27 GMT+1000 (AEST)              */
/* Path: ./auto-coded/systems/thomas-sys/plant_model.hpp */
/* Generator mark: G54168791813                          */
/*********************************************************/
#pragma once

#include <auto-coded/systems/thomas-sys/manager.hpp>


void ThomasSys_plant_init_states(double /*t*/,position& /*states0*/);

void ThomasSys_plant_manual_inits(
		ThomasSys_manager& system);

void ThomasSys_plant_manual_finalize(
		ThomasSys_manager& system);

void ThomasSys_plant_rhs(
		const position &state,
		position &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void ThomasSys_plant_observer(
		bool &/*simulation_continue*/,
		const position &state,
		const double t,
		const double /*observed_t*/,
		position &output);

