/*********************************************************/
/* Warning: Autogenerated and subjected to change        */
/* Sat Sep 08 2014 13:23:33 GMT+1000 (AEST)              */
/* Path: ./auto-coded/systems/windmi-sys/plant_model.hpp */
/* Generator mark: G54168791813                          */
/*********************************************************/
#pragma once

#include <auto-coded/systems/windmi-sys/manager.hpp>


void WINDMISys_plant_init_states(double /*t*/,position& /*states0*/);

void WINDMISys_plant_manual_inits(
		WINDMISys_manager& system);

void WINDMISys_plant_manual_finalize(
		WINDMISys_manager& system);

void WINDMISys_plant_rhs(
		const position &state,
		position &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void WINDMISys_plant_observer(
		bool &/*simulation_continue*/,
		const position &state,
		const double t,
		const double /*observed_t*/,
		position &output);

