/*****************************************************/
/* Warning: Autogenerated and subjected to change    */
/* Sun Apr 15 2014 20:03:52 GMT+1000 (AEST)          */
/* Path: ./auto-coded/systems/arneodosys/manager.cpp */
/* Generator mark: G7692348073                       */
/*****************************************************/
#include <auto-coded/systems/arneodosys/manager.hpp>
#include <auto-coded/systems/arneodosys/solver.hpp>
#include <auto-coded/systems/arneodosys/plant_model.hpp>


ArneodoSys_manager::ArneodoSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t ArneodoSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=15044.0;
	double dt=0.001;
	ArneodoSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	ArneodoSys_plant_init_states(t_start,plant_state);
	ArneodoSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	ArneodoSys_plant_manual_finalize(*this);
	return integrate_result;
}

void ArneodoSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	ArneodoSys_plant_rhs(state,state_dot,t,observed_t);
}

void ArneodoSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	ArneodoSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

