/*********************************************************/
/* Warning: Autogenerated and subjected to change        */
/* Sun Apr 15 2014 20:03:52 GMT+1000 (AEST)              */
/* Path: ./auto-coded/systems/arneodosys/plant_model.hpp */
/* Generator mark: G54168791813                          */
/*********************************************************/
#pragma once

#include <auto-coded/systems/arneodosys/manager.hpp>


void ArneodoSys_plant_init_states(double /*t*/,position& /*states0*/);

void ArneodoSys_plant_manual_inits(
		ArneodoSys_manager& system);

void ArneodoSys_plant_manual_finalize(
		ArneodoSys_manager& system);

void ArneodoSys_plant_rhs(
		const position &state,
		position &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void ArneodoSys_plant_observer(
		bool &/*simulation_continue*/,
		const position &state,
		const double t,
		const double /*observed_t*/,
		position &output);

