/**************************************************/
/* Warning: Autogenerated and subjected to change */
/* Sun May 27 2014 15:53:17 GMT+1000 (AEST)       */
/* Path: ./auto-coded/systems/chuasys/manager.cpp */
/* Generator mark: G7692348073                    */
/**************************************************/
#include <auto-coded/systems/chuasys/manager.hpp>
#include <auto-coded/systems/chuasys/solver.hpp>
#include <auto-coded/systems/chuasys/plant_model.hpp>


ChuaSys_manager::ChuaSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t ChuaSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=500.0;
	double dt=0.001;
	ChuaSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	ChuaSys_plant_init_states(t_start,plant_state);
	ChuaSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	ChuaSys_plant_manual_finalize(*this);
	return integrate_result;
}

void ChuaSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	ChuaSys_plant_rhs(state,state_dot,t,observed_t);
}

void ChuaSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	ChuaSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

