/****************************************************/
/* Warning: Autogenerated and subjected to change   */
/* Wed Mar 21 2014 10:49:03 GMT+1100 (AEDT)         */
/* Path: ./auto-coded/systems/lorenzsys/manager.cpp */
/* Generator mark: G7692348073                      */
/****************************************************/
#include <auto-coded/systems/lorenzsys/manager.hpp>
#include <auto-coded/systems/lorenzsys/solver.hpp>
#include <auto-coded/systems/lorenzsys/plant_model.hpp>


LorenzSys_manager::LorenzSys_manager():
			observed_t(0.0)
{
}

size_t LorenzSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=200.0;
	double dt=0.01;
	LorenzSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	LorenzSys_plant_init_states(t_start,plant_state);
	LorenzSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	LorenzSys_plant_manual_finalize(*this);
	return integrate_result;
}

void LorenzSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	LorenzSys_plant_rhs(state,state_dot,t,observed_t);
}

void LorenzSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	LorenzSys_plant_observer(state,t,observed_t,plant_output);
	observed_t=t;
}

