/********************************************************/
/* Warning: Autogenerated and subjected to change       */
/* Wed Mar 21 2014 10:49:03 GMT+1100 (AEDT)             */
/* Path: ./auto-coded/systems/lorenzsys/plant_model.hpp */
/* Generator mark: G54168791813                         */
/********************************************************/
#pragma once

#include <auto-coded/systems/lorenzsys/manager.hpp>


void LorenzSys_plant_init_states(double /*t*/,position& /*states0*/);

void LorenzSys_plant_manual_inits(
		LorenzSys_manager& system);

void LorenzSys_plant_manual_finalize(
		LorenzSys_manager& system);

void LorenzSys_plant_rhs(
		const position &state,
		position &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void LorenzSys_plant_observer(
		const position &state,
		const double t,
		const double /*observed_t*/,
		position &output);

