#!/bin/bash
####################################################
#  Warning: Autogenerated and subjected to change  #
#  Wed Mar 21 2014 10:49:03 GMT+1100 (AEDT)        #
#  Path: ./debug_build.sh                          #
#  Generator mark: G54168428419                    #
####################################################

cmake -DCMAKE_BUILD_TYPE=Debug -H. -B_built_d && cd _built_d && make && cp ./chaos_lorenz ../
