#!/bin/bash
####################################################
#  Warning: Autogenerated and subjected to change  #
#  Wed Mar 21 2014 10:49:03 GMT+1100 (AEDT)        #
#  Path: ./release_build.sh                        #
#  Generator mark: G6416149813                     #
####################################################

cmake -DCMAKE_BUILD_TYPE=Release -H. -B_built_r && cd _built_r && make && cp ./chaos_lorenz ../
