/**************************************************/
/* Warning: Autogenerated and subjected to change */
/* Sun May 27 2014 14:57:49 GMT+1000 (AEST)       */
/* Path: ./auto-coded/systems/actsys/manager.cpp  */
/* Generator mark: G7692348073                    */
/**************************************************/
#include <auto-coded/systems/actsys/manager.hpp>
#include <auto-coded/systems/actsys/solver.hpp>
#include <auto-coded/systems/actsys/plant_model.hpp>


actSys_manager::actSys_manager():
			simulation_continue(true),
			observed_t(0.0)
{
}

size_t actSys_manager::integrate()
{
	double t_start=0.0;
	double t_stop=15044.0;
	double dt=0.001;
	actSys_plant_manual_inits(*this);
	position plant_state;
	plant_state.reset();
	plant_output.reset();
	actSys_plant_init_states(t_start,plant_state);
	actSys_solver solver(*this);
	size_t integrate_result=solver.integrate(plant_state,t_start,t_stop,dt);
	actSys_plant_manual_finalize(*this);
	return integrate_result;
}

void actSys_manager::plant_rhs(
	const position &state,
	position &state_dot,
	const double t)
{
	actSys_plant_rhs(state,state_dot,t,observed_t);
}

void actSys_manager::plant_observer(
		const position &state,
		const double t,
		const double /*dt*/)
{
	actSys_plant_observer(simulation_continue,state,t,observed_t,plant_output);
	observed_t=t;
}

