#!/bin/bash
####################################################
#  Warning: Autogenerated and subjected to change  #
#  Thu Oct 18 2014 22:29:14 GMT+1100 (AEDT)        #
#  Path: ./release_build.sh                        #
#  Generator mark: G6416149813                     #
####################################################

cmake -DCMAKE_BUILD_TYPE=Release -H. -B_built_r && cd _built_r && make && cp ./galaxy_spherical_single ../
