/****************************************************/
/* Warning: Autogenerated and subjected to change   */
/* Thu Oct 18 2014 22:29:06 GMT+1100 (AEDT)         */
/* Path: ./auto-coded/systems/galaxysys/manager.hpp */
/* Generator mark: G7692348073                      */
/****************************************************/
#pragma once

#include <cstddef>
#include <auto-coded/types/galaxy.hpp>

using std::size_t;

class GalaxySys_manager
{
public:
	// fields
	bool simulation_continue;
	double observed_t;
	Galaxy plant_output;

	// methods
	GalaxySys_manager();

	size_t integrate();

	void plant_rhs(
		const Galaxy &state,
		Galaxy &state_dot,
		const double t);

	void plant_observer(
		const Galaxy &state,
		const double t,
		const double dt);

};

