/********************************************************/
/* Warning: Autogenerated and subjected to change       */
/* Thu Oct 18 2014 22:29:06 GMT+1100 (AEDT)             */
/* Path: ./auto-coded/systems/galaxysys/plant_model.hpp */
/* Generator mark: G54168791813                         */
/********************************************************/
#pragma once

#include <auto-coded/systems/galaxysys/manager.hpp>


void GalaxySys_plant_init_states(double /*t*/,Galaxy& /*states0*/);

void GalaxySys_plant_manual_inits(
		GalaxySys_manager& system);

void GalaxySys_plant_manual_finalize(
		GalaxySys_manager& system);

void GalaxySys_plant_rhs(
		const Galaxy &state,
		Galaxy &state_dot,
		const double /*t*/,
		const double /*observed_t*/);

void GalaxySys_plant_observer(
		bool &/*simulation_continue*/,
		const Galaxy &state,
		const double t,
		const double /*observed_t*/,
		Galaxy &output);

